### ISSUE TITLE
为什么 parseInt(0.0000008) === 8？

### ISSUE THREAD

**Issue by Alvin-Liu** [Alvin-Liu/Blog#6]
parseInt() 函数可解析一个字符串，并返回一个整数

语法：

    parseInt(string, radix)

- string：必需。要被解析的字符串
- radix：可选。表示要解析的数字的基数。该值介于 2 ~ 36 之间。如果省略该参数或其值为 0，则数字将以 10 为基础来解析。如果它以 “0x” 或 “0X” 开头，将以 16 为基数。如果该参数小于 2 或者大于 36，则 parseInt() 将返回 NaN

特例：

    parseInt(1000000000000000000000.5, 10); // 1

为什么会这样呢？

parseInt 的第一个类型是字符串，所以会将传入的参数转换成字符串，也就是 String(1000000000000000000000.5) 的结果为 '1e+21'。parseInt 并没有将 'e' 视为一个数字，所以在转换到 1 后就停止了。

这也就可以解释 parseInt(0.0000008) === 8：

    String(0.000008);  // '0.000008'
    String(0.0000008); // '8e-7'

悲剧：

    parseInt(1/0, 19);      // 18
    parseInt(false, 16);    // 250
    parseInt(parseInt, 16); // 15
    parseInt("0x10");       // 16
    parseInt("10", 2);      // 2

[http://blog.csdn.net/Vanhukseter/article/details/43459927](http://blog.csdn.net/Vanhukseter/article/details/43459927 "http://blog.csdn.net/Vanhukseter/article/details/43459927")

[http://www.jianshu.com/p/8fcfabb09792](http://www.jianshu.com/p/8fcfabb09792 "http://www.jianshu.com/p/8fcfabb09792")

位运算
[https://www.cnblogs.com/xljzlw/p/4231354.html](https://www.cnblogs.com/xljzlw/p/4231354.html)

**Comment by xuoutput** [comment]
学到了
